export const failure_list = [
    'Natural disasters',
    'Cyber attacks',
    'Human error',
    'Equipment failure',
    'Supply chain disruptions',
    'Power outages',
    'Communication failures',
    'Infrastructure failures',
    'Legal and regulatory compliance failures',
    'Reputation damage',
    'Pandemics and health emergencies',
    'Financial crises',
    'Political instability',
    'Terrorism and acts of violence',
    'System failures',
    'Data breaches',
    'Intellectual property theft',
    'Employee sabotage',
    'Environmental disasters',
    'Economic downturns',
    'Loss of key personnel',
    'Fraud and embezzlement',
    'Public relations crises',
    'Operational errors',
    'Management and leadership failures',
    'Social media attacks',
    'Mistakes in decision making',
    'Failure to innovate',
    'Customer complaints and dissatisfaction',
    'Competitor actions'
];

export const industryList = [
    "Agriculture",
    "Automotive",
    "Chemicals",
    "Communications",
    "Construction",
    "Consumer goods",
    "Education",
    "Energy",
    "Financial services",
    "Healthcare",
    "Hospitality and tourism",
    "Information technology",
    "Manufacturing",
    "Media and entertainment",
    "Mining and metals",
    "Pharmaceuticals",
    "Real estate",
    "Retail",
    "Transportation and logistics",
    "Utilities",
    "Aerospace and defense",
    "Advertising and marketing",
    "Architecture and design",
    "Biotechnology and life sciences",
    "Consulting",
    "Environmental services",
    "Food and beverage",
    "Government and public administration",
    "Human resources and staffing",
    "Insurance",
    "Legal services",
    "Nonprofit and social services",
    "Professional services",
    "Telecommunications",
    "Waste management and recycling",
    "Wholesale and distribution"
];



export const returnToTime = [
    "4 hours",
    "8 hours",
    "1 day",
    "2 days",
    "3 days",
    "One week",
    "Two weeks",
    "One month",
    "More than one month"
];


