import Image from 'next/image'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-full flex flex-col bg-gradient-to-r from-[#537FE7] to-[#1D2F58]">
        <div className='w-full'>
          <Image src="/logo.png" className='p-4' width={200} height={200} alt="1 icon" />
        </div>
        {children}
      </body>
    </html>
  )
}
